FROM centos:latest
MAINTAINER csramesh1@gmail.com
RUN yum install wget -y
RUN wget --no-cookies --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' \
         'http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz' >> /usr/sbin/jdk
RUN tar -xvzf 'jdk-8u171-linux-x64.tar.gz' >> /usr/sbin/jdk
ENV JAVA_HOME /usr/sbin/jdk/jdk-1.8.0
RUN echo "export PATH=$PATH:${JAVA_HOME}/bin" >> ~/.bashrc
CMD ["bash"]



