FROM centos:latest
MAINTAINER csramesh1@gmail.com
RUN yum install wget -y 
RUN echo --no-cookies --no-check-certificate --header 'Cookie: oraclelicence=accept-securebackup-cookie' >> /usr/local/jdk
WORKDIR /jdk
RUN wget "http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jdk-10.0.1_linux-x64_bin.tar.gz" 
ENV JAVA_HOME /usr/local/jdk/jdk-10.0.1
RUN echo 'export PATH=${JAVA_HOME}/bin:$PATH' | tee ~/.bashrc
CMD ["bash"]


